### PR TITLE
Added support for Guzzle v6, psr-2 format, added gitignore

### LINKED ISSUE #33: Mailtrap trait error with Guzzle 6
For the past hour or so Ive been wrestling with why my previously working tests were all of a sudden failing. I hadn't realised that during a previous composer update Guzzle had upgrade to version 6. Using 6 i get the following error when trying to use the Mailtrap trait...

cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (GuzzleHttp\Exception\RequestException)

Downgrading to Guzzle 5 meant this worked correctly. Not sure what the root cause is here, but it was a painful bug to figure out (for me anyway) so want to alert anyone who may run into the same issue. Might be worth looking into fixing or requiring version 5?

Keep up the good work Jeffrey :)

### PR DESCRIPTION
**Pull request by jakubhomoly**
Fixes #33, #37

### CODE REVIEW

**Comment by timbroder** [comment]
Thanks @insanesvk!

**Comment by ifdattic** [comment]
Thanks @insanesvk 

As this is not merged updated my composer to install from your repository and require `dev-master` version of package.

``` json
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/insanesvk/Behat-Laravel-Extension"
        }
    ]
```

**Comment by jakubhomoly** [comment]
No probs! Glad I could be of help. Thanks @ifdattic for the composer information, it's going to help others :)

**Comment by alnutile** [comment]
Seems like this was now merged in via other commits? Sorry for the delay I totally overlooked the PR queue. :(
I will close this for now but if something did not make it in please feel free to post again and I will merge in within a day or so.

**Comment by g0ld3lux** [comment]
is this already merged to master branch?

**Pull request closed without merging**
